package com.mushiny.wms.internaltool.common.enums;

public enum StockUnitRecordState {

    STOW_LOSS_GOODS_RECORD_CODE("P"),
    STOW_LOSS_GOODS_RECORD_TOOL("IB Problem Solve"),
    STOW_LOSS_GOODS_RECORD_TYPE("STOW LOSS"),

    STOW_OVERAGE_GOODS_RECORD_CODE("P"),
    STOW_OVERAGE_GOODS_RECORD_TOOL("IB Problem Solve"),
    STOW_OVERAGE_GOODS_RECORD_TYPE("STOW OVERAGE"),

    LOSS_GOODS_RECORD_CODE("P"),
    LOSS_GOODS_RECORD_TOOL("IB Problem Solve"),
    LOSS_GOODS_RECORD_TYPE("INVENTORY LOSS"),

    OVERAGE_GOODS_RECORD_CODE("P"),
    OVERAGE_GOODS_RECORD_TOOL("IB Problem Solve"),
    OVERAGE_GOODS_RECORD_TYPE("INVENTORY OVERAGE"),

    ENTRY_LOT_RECORD_TOOL("Entry Lot Tool"),

    MOVE_GOODS_RECORD_CODE("P"),
    MOVE_GOODS_RECORD_TOOL("Move Item Tool"),
    MOVE_GOODS_RECORD_TYPE("MOVE ITEM"),

    MEASURE_GOODS_RECORD_CODE("M"),
    MEASURE_GOODS_RECORD_TOOL("Measure"),
    MEASURE_GOODS_RECORD_TYPE("MEASURE"),


    UPDATE_INVENTORY_STATE_RECORD_MOVE_ITEM_CODE("P"),
    UPDATE_INVENTORY_STATE_RECORD_MOVE_ITEM_TOOL("Adjust Tool"),
    UPDATE_INVENTORY_STATE_RECORD_MOVE_ITEM_TYPE("MOVE ITEM"),

    UPDATE_INVENTORY_STATE_RECORD_INVENTORY_OVERAGE_CODE("P"),
    UPDATE_INVENTORY_STATE_RECORD_INVENTORY_OVERAGE_TOOL("Adjust Tool"),
    UPDATE_INVENTORY_STATE_RECORD_INVENTORY_OVERAGE_TYPE("INVENTORY OVERAGE"),

    UPDATE_INVENTORY_STATE_RECORD_INVENTORY_LOSS_CODE("P"),
    UPDATE_INVENTORY_STATE_RECORD_INVENTORY_LOSS_TOOL("Adjust Tool"),
    UPDATE_INVENTORY_STATE_RECORD_INVENTORY_LOSS_TYPE("INVENTORY LOSS"),

    UPDATE_INVENTORY_STATE_RECORD_CHANGE_PROPERTY_CODE("P"),
    UPDATE_INVENTORY_STATE_RECORD_CHANGE_PROPERTY_TOOL("Adjust Tool"),
    UPDATE_INVENTORY_STATE_RECORD_CHANGE_PROPERTY_TYPE("CHANGE PROPERTY"),

    UPDATE_INVENTORY_STATE_RECORD_MOVE_CONTAINER_CODE("P"),
    UPDATE_INVENTORY_STATE_RECORD_MOVE_CONTAINER_TOOL("Adjust Tool"),
    UPDATE_INVENTORY_STATE_RECORD_MOVE_CONTAINER_TYPE("MOVE CONTAINER");

    private String name;//定义自定义的变量

    StockUnitRecordState(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
