package com.mushiny.wms.outboundproblem.business.enums;

public enum StockUnitRecordState {

    STOW_LOSS_GOODS_RECORD_CODE_REBIN("P"),
    STOW_LOSS_GOODS_RECORD_TOOL_REBIN("OB Problem Check"),
    STOW_LOSS_GOODS_RECORD_TYPE_REBIN("REBIN LOSS"),

    STOW_LOSS_GOODS_RECORD_CODE_PACK("P"),
    STOW_LOSS_GOODS_RECORD_TOOL_PACK("OB Problem Check"),
    STOW_LOSS_GOODS_RECORD_TYPE_PACK("PACK LOSS"),

    STOW_OVERAGE_GOODS_RECORD_CODE_REBIN("P"),
    STOW_OVERAGE_GOODS_RECORD_TOOL_REBIN("OB Problem Check"),
    STOW_OVERAGE_GOODS_RECORD_TYPE_REBIN("REBIN OVERAGE"),

    STOW_OVERAGE_GOODS_RECORD_CODE_PACK("P"),
    STOW_OVERAGE_GOODS_RECORD_TOOL_PACK("OB Problem Check"),
    STOW_OVERAGE_GOODS_RECORD_TYPE_PACK("PACK OVERAGE"),


    LOSS_GOODS_RECORD_CODE("P"),
    LOSS_GOODS_RECORD_TOOL("OB Problem Check"),
    LOSS_GOODS_RECORD_TYPE("INVERTORY LOSS"),

    OVERAGE_GOODS_RECORD_CODE("P"),
    OVERAGE_GOODS_RECORD_TOOL("OB Problem Check"),
    OVERAGE_GOODS_RECORD_TYPE("INVERTORY OVERAGE"),





    OB_PROBLEM_SOLVE_RECORD_CODE("P"),
    OB_PROBLEM_SOLVE_RECORD_TOOL("OB Problem Solve"),
    OB_PROBLEM_SOLVE_RECORD_TYPE("OB PROBLEM SOLVE"),

    MOVE_GOODS_RECORD_CODE("M"),
    MOVE_GOODS_RECORD_TOOL("Tools"),
    MOVE_GOODS_RECORD_TYPE("MoveGoods"),

    MEASURE_GOODS_RECORD_CODE("M"),
    MEASURE_GOODS_RECORD_TOOL("Tools"),
    MEASURE_GOODS_RECORD_TYPE("MeasureGoods"),

    UPDATE_INVENTORY_STATE_RECORD_CODE("M"),
    UPDATE_INVENTORY_STATE_RECORD_TOOL("Tools"),
    UPDATE_INVENTORY_STATE_RECORD_TYPE("UpdateInventoryAttributes");

    private String name;//定义自定义的变量

    StockUnitRecordState(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
