# Pending
SELECT COALESCE((AMOUNT1 - AMOUNT2), 0) AS pending
FROM
  ((SELECT COALESCE(SUM(CSP.AMOUNT), 0) AS AMOUNT1
    FROM OB_CUSTOMERSHIPMENT CS
      LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
    WHERE CS.DELIVERY_DATE = :exsdTime) A
    LEFT JOIN
    (SELECT COALESCE(SUM(CSP.AMOUNT), 0) AS AMOUNT2
     FROM OB_CUSTOMERSHIPMENT CS
       LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
     WHERE CSP.ID IN
           (SELECT DISTINCT POP.CUSTOMERSHIPMENTPOSITION_ID
            FROM OB_PICKINGORDERPOSITION POP
              LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID) AND CS.DELIVERY_DATE = :exsdTime) A1 ON 1 = 1
  );

# 1.ReadyToPick
SELECT coalesce(SUM(POP.AMOUNT), 0) AS ReadyToPick
FROM OB_PICKINGORDERPOSITION POP
WHERE POP.PICKINGORDER_ID IS NULL
      AND POP.CUSTOMERSHIPMENTPOSITION_ID
          IN (SELECT CSP.ID
              FROM OB_CUSTOMERSHIPMENTPOSITION CSP
                LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
              WHERE CS.DELIVERY_DATE = :exsdTime);

# 2.PickingNotYetPicked
SELECT coalesce(SUM(CSP.AMOUNT - CSP.AMOUNT_PICKED), 0) AS PickingNotYetPicked
FROM
  OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
WHERE CS.DELIVERY_DATE = :exsdTime
      AND CSP.STATE <= '600';

# 3.PickingPicked
SELECT coalesce(SUM(POP.AMOUNT_PICKED), 0) AS PickingPicked
FROM
  OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN OB_PICKINGORDERPOSITION POP ON CSP.ID = POP.CUSTOMERSHIPMENTPOSITION_ID
  LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
WHERE
  CS.DELIVERY_DATE = :exsdTime
  AND (CSP.STATE <= '600' OR (CSP.STATE = '605' AND PUL.STATE = '600'));

# 4.Rebatched
SELECT coalesce(SUM(POP.AMOUNT_PICKED), 0) AS Rebatched
FROM OB_PICKINGORDERPOSITION POP
  LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
WHERE POP.CUSTOMERSHIPMENTPOSITION_ID
      IN (SELECT CSP.ID
          FROM OB_CUSTOMERSHIPMENTPOSITION CSP
            LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
          WHERE CS.DELIVERY_DATE = :exsdTime
                AND (CS.STATE = '610' OR CS.STATE = '605'))
      AND PUL.STATE = '610';

# 5.RebinBuffer
SELECT COALESCE(SUM(POP.AMOUNT - POP.AMOUNT_REBINED), 0) AS amount
FROM OB_CUSTOMERSHIPMENTPOSITION POP
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON POP.SHIPMENT_ID = CS.ID
WHERE CS.DELIVERY_DATE = :exsdTime
      AND POP.STATE = '620'
      AND POP.ID NOT IN
          (SELECT RBP.CUSTOMERSHIPMENTPOSITION_ID
           FROM OB_REBINREQUESTPOSITION RBP
           WHERE RBP.STATE = 'LOSE');
;

# 6.Rebined
SELECT COALESCE(SUM(amount), 0) AS Rebined
FROM (

       (SELECT COALESCE(SUM(POP.AMOUNT_REBINED), 0) AS amount
        FROM OB_CUSTOMERSHIPMENTPOSITION POP
          LEFT JOIN OB_CUSTOMERSHIPMENT CS ON POP.SHIPMENT_ID = CS.ID
        WHERE
          CS.DELIVERY_DATE = :exsdTime
          AND POP.ID IN (
            SELECT DISTINCT POP.ID
            FROM OB_CUSTOMERSHIPMENTPOSITION POP
              LEFT JOIN OB_PICKINGORDERPOSITION P ON POP.ID = P.CUSTOMERSHIPMENTPOSITION_ID
              LEFT JOIN OB_PICKINGORDER PO ON P.PICKINGORDER_ID = PO.ID
            WHERE PO.STATE = '700'
                  AND CS.STATE = '630'
          )
          AND CS.ID NOT IN (SELECT CS.ID
                            FROM OB_CUSTOMERSHIPMENT CS
                            WHERE CS.STATE = '1100'))
       UNION ALL
       (SELECT COALESCE(SUM(POP.AMOUNT_REBINED), 0) AS amount
        FROM OB_CUSTOMERSHIPMENTPOSITION POP
          LEFT JOIN OB_CUSTOMERSHIPMENT CS ON POP.SHIPMENT_ID = CS.ID
        WHERE
          CS.DELIVERY_DATE = :exsdTime
          AND POP.ID IN (
            SELECT DISTINCT POP.ID
            FROM OB_CUSTOMERSHIPMENTPOSITION POP
              LEFT JOIN OB_PICKINGORDERPOSITION P ON POP.ID = P.CUSTOMERSHIPMENTPOSITION_ID
              LEFT JOIN OB_PICKINGORDER PO ON P.PICKINGORDER_ID = PO.ID
            WHERE PO.STATE <> '700'
          )
       )) A;

# 7.ScanVerify
SELECT coalesce(SUM(CSP.AMOUNT), 0) AS ScanVerify
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_PACKINGREQUEST PR ON CS.ID = PR.CUSTOMERSHIPMENT_ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
WHERE
  CS.DELIVERY_DATE = :exsdTime
  AND CS.STATE = 640;

# 8.Packed
SELECT coalesce(SUM(CSP.AMOUNT), 0) AS Packed
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
WHERE CS.STATE = '650'
      AND CS.DELIVERY_DATE = :exsdTime;

# 9.Problem
SELECT DISTINCT coalesce(SUM(CSP.AMOUNT), 0) AS Problem
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
WHERE
  CS.DELIVERY_DATE = :exsdTime
  AND CSP.ID
      IN (SELECT DISTINCT CSP.ID
          FROM OB_CUSTOMERSHIPMENTPOSITION CSP
            LEFT JOIN OB_PICKINGORDERPOSITION PC ON CSP.ID = PC.CUSTOMERSHIPMENTPOSITION_ID
            LEFT JOIN OB_PICKINGORDER PR ON PC.PICKINGORDER_ID = PR.ID
          WHERE CS.state = '1100'
                AND PR.STATE = '700'
      );

# 10.Sorted
SELECT coalesce(SUM(CSP.AMOUNT), 0) AS Sorted
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
WHERE CS.STATE = '660'
      AND CS.DELIVERY_DATE = :exsdTime;

# 11.Loaded
SELECT coalesce(SUM(CSP.AMOUNT), 0) AS Loaded
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
WHERE CS.STATE = '670'
      AND CS.DELIVERY_DATE = :exsdTime;




