/*1. StockEnough 明细 */
SELECT
  CS.SHIPMENT_NO   AS shipmentID,
  CO.ORDER_NO      AS orderID,
  BT.NAME          AS boxType,
  ITD.SKU_NO       AS SKUNO,
  ITD.ITEM_NO      AS SKUID,
  CSP.AMOUNT       AS quality,
  CS.DELIVERY_DATE AS planDepartTime,
  ''               AS stockPosition1,
  ''               AS stockPosition2,
  'Stock enough'   AS workFlowStatus,
  ''               AS ppName,
  ''               AS batchNo
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_PICKINGORDERPOSITION POP ON CSP.ID = POP.CUSTOMERSHIPMENTPOSITION_ID
  LEFT JOIN INV_STOCKUNIT SU ON POP.PICKFROMSTOCKUNIT_ID = SU.ID
  LEFT JOIN OB_PICKINGUNITLOAD RUL ON POP.PICKTOUNITLOAD_ID = RUL.ID
  LEFT JOIN INV_UNITLOAD UL ON RUL.UNITLOAD_ID = UL.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
WHERE CS.STATE = 550
      AND CS.DELIVERY_DATE = ''
      AND UL.STORAGELOCATION_ID
          IN (SELECT STL.ID
              FROM MD_STORAGELOCATION STL LEFT JOIN MD_AREA A
                  ON STL.AREA_ID = A.ID
              WHERE A.NAME = 'Picking_Zone');

/*2. Replenishing 明细*/
SELECT
  A.SHIPMENT_NO          AS shipmentID,
  A.ORDER_NO             AS orderID,
  A.NAME                 AS boxType,
  A.SKU_NO               AS SKUNO,
  A.ITEM_NO              AS SKUID,
  A.AMOUNT               AS quality,
  A.DELIVERY_DATE        AS planDepartTime,
  B.FROM_STORAGELOCATION AS stockPosition1,
  B.STORAGELOCATION_ID   AS stockPosition2,
  'Replenishing'         AS workFlowStatus,
  ''                     AS ppName,
  ''                     AS batchNo
FROM
  (SELECT
     CSP.ITEMDATA_ID,
     CSP.ID,
     CS.SHIPMENT_NO,
     CO.ORDER_NO,
     BT.NAME,
     ITD.SKU_NO,
     ITD.ITEM_NO,
     CSP.AMOUNT,
     CS.DELIVERY_DATE,
     CS.SORT_CODE
   FROM OB_CUSTOMERSHIPMENT CS
     LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
     LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
     LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
     LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
   WHERE CS.DELIVERY_DATE = ''
         AND CS.STATE = 0) A,
  (SELECT
     STU.ITEMDATA_ID,
     SUR.FROM_STORAGELOCATION,
     UL.STORAGELOCATION_ID
   FROM INV_STOCKUNIT STU
     LEFT JOIN INV_STOCKUNITRECORD SUR ON STU.ID = SUR.TO_STOCKUNIT
     LEFT JOIN INV_UNITLOAD UL ON STU.UNITLOAD_ID = UL.ID
   WHERE SUR.FROM_STORAGELOCATION
         IN (SELECT STL.NAME
             FROM MD_STORAGELOCATION STL
               LEFT JOIN MD_AREA A ON STL.AREA_ID = A.ID
             WHERE A.NAME = 'Buffer_Zone')) B
WHERE A.ITEMDATA_ID = B.ITEMDATA_ID;

/*3. TotalReplenishment 明细*/
SELECT
  CS.SHIPMENT_NO        AS shipmentID,
  CO.ORDER_NO           AS orderID,
  BT.NAME               AS boxType,
  ITD.SKU_NO            AS SKUNO,
  ITD.ITEM_NO           AS SKUID,
  CSP.AMOUNT            AS quality,
  CS.DELIVERY_DATE      AS planDepartTime,
  ''                    AS stockPosition1,
  ''                    AS stockPosition2,
  'Total Replenishment' AS workFlowStatus,
  ''                    AS ppName,
  ''                    AS batchNo
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
WHERE CS.STATE = 550
      AND CS.DELIVERY_DATE = '';

/*4. ReadyToPick 明细*/
SELECT
  CS.SHIPMENT_NO     AS shipmentID,
  CS.CUSTOMER_NAME   AS orderID,
  BT.NAME            AS boxType,
  ITD.SKU_NO         AS SKUNO,
  ITD.ITEM_NO        AS SKUID,
  POP.AMOUNT         AS quality,
  CS.DELIVERY_DATE   AS planDepartTime,
  SL.NAME            AS stockPosition1,
  ''                 AS stockPosition2,
  'Ready to Pick'    AS workFlowStatus,
  PP.NAME            AS ppName,
  PO.PICKINGORDER_NO AS batchNo
FROM OB_PICKINGORDERPOSITION POP
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON POP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_PICKINGCATEGORY PC ON CS.PICKINGCATEGORY_ID = PC.ID
  LEFT JOIN OB_PROCESSPATH PP ON PC.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
  LEFT JOIN INV_STOCKUNIT ST ON POP.PICKFROMSTOCKUNIT_ID = ST.ID
  LEFT JOIN INV_UNITLOAD UL ON ST.UNITLOAD_ID = UL.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
WHERE
  #   POP.STATE = '200' and
  POP.CUSTOMERSHIPMENTPOSITION_ID
  IN (SELECT CSP.ID
      FROM OB_CUSTOMERSHIPMENTPOSITION CSP
        LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
      WHERE CS.DELIVERY_DATE = '2017-08-16 03:00:00');

/*5. PickingNotYetPicked 明细*/
SELECT
  CS.SHIPMENT_NO                   AS shipmentID,
  CS.CUSTOMER_NAME                 AS orderID,
  BT.NAME                          AS boxType,
  ITD.SKU_NO                       AS SKUNO,
  ITD.ITEM_NO                      AS SKUID,
  (POP.AMOUNT - POP.AMOUNT_PICKED) AS quality,
  CS.DELIVERY_DATE                 AS planDepartTime,
  SL.NAME                          AS stockPosition1,
  ''                               AS stockPosition2,
  'Picking Not Yet Picked'         AS workFlowStatus,
  PP.NAME                          AS ppName,
  PO.PICKINGORDER_NO               AS batchNo
FROM OB_PICKINGORDERPOSITION POP
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON POP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
  LEFT JOIN INV_STOCKUNIT ST ON POP.PICKFROMSTOCKUNIT_ID = ST.ID
  LEFT JOIN INV_UNITLOAD UL ON ST.UNITLOAD_ID = UL.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
WHERE PO.STATE < 600
      AND POP.CUSTOMERSHIPMENTPOSITION_ID
          IN (SELECT CSP.ID
              FROM OB_CUSTOMERSHIPMENTPOSITION CSP
                LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
              WHERE CS.DELIVERY_DATE = '2017-08-16 03:00:00')
      AND POP.PICKINGORDER_ID IS NOT NULL
      AND (POP.AMOUNT - POP.AMOUNT_PICKED) > 0;

/*2017.8.8.  new new 更新PickingPicked 明细*/
SELECT DISTINCT
  CS.SHIPMENT_NO                   AS shipmentID,
  CS.CUSTOMER_NAME                 AS orderID,
  BT.NAME                          AS boxType,
  ITD.SKU_NO                       AS SKUNO,
  ITD.ITEM_NO                      AS SKUID,
  coalesce((CSP.AMOUNT_PICKED), 0) AS quality,
  CS.DELIVERY_DATE                 AS planDepartTime,
  SL.NAME                          AS stockPosition1,
  SL.ID,
  UL.STORAGELOCATION_ID,
  ''                               AS stockPosition2,
  'PickingPicked'                  AS workFlowStatus,
  PP.NAME                          AS ppName,
  PO.PICKINGORDER_NO               AS batchNo
FROM
  OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN OB_PICKINGORDERPOSITION POP ON CSP.ID = POP.CUSTOMERSHIPMENTPOSITION_ID
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
  LEFT JOIN INV_UNITLOAD UL ON PUL.UNITLOAD_ID = UL.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
WHERE
  CS.DELIVERY_DATE = '2017-09-02 13:30:00'
  AND CSP.STATE <= '600'
  AND CSP.AMOUNT_PICKED > 0;


/*6. 更新PickingPicked 明细*/
SELECT DISTINCT
  CS.SHIPMENT_NO                   AS shipmentID,
  CS.CUSTOMER_NAME                 AS orderID,
  BT.NAME                          AS boxType,
  ITD.SKU_NO                       AS SKUNO,
  ITD.ITEM_NO                      AS SKUID,
  coalesce((CSP.AMOUNT_PICKED), 0) AS quality,
  CS.DELIVERY_DATE                 AS planDepartTime,
  SL.NAME                          AS stockPosition1,
  ''                               AS stockPosition2,
  'PickingPicked'                  AS workFlowStatus,
  PP.NAME                          AS ppName,
  PO.PICKINGORDER_NO               AS batchNo
FROM
  OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
WHERE CS.DELIVERY_DATE = '2017-09-02 13:30:00'
      AND CSP.STATE <= '600'
      AND CSP.AMOUNT_PICKED > 0
      AND CSP.ID IN (SELECT DISTINCT POP.CUSTOMERSHIPMENTPOSITION_ID
                     FROM OB_PICKINGORDERPOSITION POP
                       #   LEFT JOIN OB_PICKINGORDERPOSITION POP ON CSP.ID = POP.CUSTOMERSHIPMENTPOSITION_ID
                       LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
                       LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
                       LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
                       LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
                       LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
                       LEFT JOIN INV_UNITLOAD UL ON PUL.UNITLOAD_ID = UL.ID
                       LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID);






/*6. PickingPicked 明细*/
SELECT
  CS.SHIPMENT_NO                   AS shipmentID,
  CS.CUSTOMER_NAME                 AS orderID,
  BT.NAME                          AS boxType,
  ITD.SKU_NO                       AS SKUNO,
  ITD.ITEM_NO                      AS SKUID,
  coalesce((POP.AMOUNT_PICKED), 0) AS quality,
  CS.DELIVERY_DATE                 AS planDepartTime,
  SL.NAME                          AS stockPosition1,
  ''                               AS stockPosition2,
  'PickingPicked'                  AS workFlowStatus,
  PP.NAME                          AS ppName,
  PO.PICKINGORDER_NO               AS batchNo
FROM OB_PICKINGORDERPOSITION POP
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
  LEFT JOIN INV_UNITLOAD UL ON PUL.UNITLOAD_ID = UL.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON POP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
WHERE POP.CUSTOMERSHIPMENTPOSITION_ID
      IN (SELECT CSP.ID
          FROM OB_CUSTOMERSHIPMENTPOSITION CSP
            LEFT JOIN OB_CUSTOMERSHIPMENT CS
              ON CSP.SHIPMENT_ID = CS.ID
          WHERE CS.DELIVERY_DATE = '2017-08-16 03:00:00'
                AND CS.STATE IN ('500', '600'))
      AND POP.AMOUNT_PICKED > 0;

# pickingpacked明细  2017.08.11 最新
SELECT
  CS.SHIPMENT_NO                   AS shipmentID,
  CS.CUSTOMER_NAME                 AS orderID,
  BT.NAME                          AS boxType,
  ITD.SKU_NO                       AS SKUNO,
  ITD.ITEM_NO                      AS SKUID,
  coalesce((POP.AMOUNT_PICKED), 0) AS quality,
  CS.DELIVERY_DATE                 AS planDepartTime,
  SL.NAME                          AS stockPosition1,
  ''                               AS stockPosition2,
  'PickingPicked'                  AS workFlowStatus,
  PP.NAME                          AS ppName,
  PO.PICKINGORDER_NO               AS batchNo
FROM OB_PICKINGORDERPOSITION POP
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
  LEFT JOIN INV_UNITLOAD UL ON PUL.UNITLOAD_ID = UL.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON POP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
WHERE
  CS.DELIVERY_DATE = '2017-09-02 13:30:00'
  AND CSP.STATE <= '600'
  AND POP.AMOUNT_PICKED > 0;









/*7. Rebatched 明细*/
SELECT
  CS.SHIPMENT_NO                   AS shipmentID,
  CS.CUSTOMER_NAME                 AS orderID,
  BT.NAME                          AS boxType,
  ITD.SKU_NO                       AS SKUNO,
  ITD.ITEM_NO                      AS SKUID,
  coalesce((POP.AMOUNT_PICKED), 0) AS quality,
  CS.DELIVERY_DATE                 AS planDepartTime,
  SL.NAME                          AS stockPosition1,
  RSL.NAME                         AS stockPosition2,
  'Rebatched'                      AS workFlowStatus,
  PP.NAME                          AS ppName,
  PO.PICKINGORDER_NO               AS batchNo
FROM OB_PICKINGORDERPOSITION POP
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
  LEFT JOIN INV_UNITLOAD UL ON PUL.UNITLOAD_ID = UL.ID
  #   LEFT JOIN CONTAINER C ON UL.CONTAINER_ID = C.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON POP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_REBATCHREQUESTPOSITION RQP ON UL.ID = RQP.SOURCE_ID
  LEFT JOIN OB_REBATCHSLOT RSL ON RQP.REBATCHSLOT_ID = RSL.ID
WHERE POP.CUSTOMERSHIPMENTPOSITION_ID
      IN (SELECT CSP.ID
          FROM OB_CUSTOMERSHIPMENTPOSITION CSP
            LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
          WHERE CS.DELIVERY_DATE = '2017-08-16 03:00:00'
                AND CS.STATE IN ('610'));

#  RebinBuffer 明细*/  最新版
SELECT
  CS.SHIPMENT_NO               AS shipmentID,
  CS.CUSTOMER_NAME             AS orderID,
  BT.NAME                      AS boxType,
  ITD.SKU_NO                   AS SKUNO,
  ITD.ITEM_NO                  AS SKUID,
  coalesce(SUM(RBP.AMOUNT), 0) AS quality,
  CS.DELIVERY_DATE             AS planDepartTime,
  RBP.REBINFROMCONTAINER_NAME  AS stockPosition1,
  ''                           AS stockPosition2,
  'Rebin Buffer'               AS workFlowStatus,
  PP.NAME                      AS ppName,
  PO.PICKINGORDER_NO           AS batchNo
FROM OB_REBINREQUESTPOSITION RBP
  LEFT JOIN OB_REBINREQUEST RQ ON RBP.REBINREQUEST_ID = RQ.ID
  LEFT JOIN OB_PICKINGORDER PO ON RQ.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON RBP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
WHERE RBP.AMOUNT_REBINED = 0
      AND RBP.CUSTOMERSHIPMENTPOSITION_ID
          IN (SELECT CSP.ID
              FROM OB_CUSTOMERSHIPMENTPOSITION CSP
                LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
              WHERE CSP.STATE = '620'
                    AND CS.DELIVERY_DATE = '2017-09-02 00:00:00')
      AND CSP.ID NOT IN
          (SELECT RBP.CUSTOMERSHIPMENTPOSITION_ID
           FROM OB_REBINREQUESTPOSITION RBP
           WHERE RBP.STATE = 'LOSE')
GROUP BY CS.SHIPMENT_NO, CS.CUSTOMER_NAME, BT.NAME, ITD.SKU_NO, ITD.ITEM_NO, CS.DELIVERY_DATE,
  RBP.REBINFROMCONTAINER_NAME, '', 'Rebin Buffer', PP.NAME, PO.PICKINGORDER_NO;
/*8. RebinBuffer 明细*/
SELECT
  CS.SHIPMENT_NO               AS shipmentID,
  CS.CUSTOMER_NAME             AS orderID,
  BT.NAME                      AS boxType,
  ITD.SKU_NO                   AS SKUNO,
  ITD.ITEM_NO                  AS SKUID,
  coalesce(SUM(RBP.AMOUNT), 0) AS quality,
  CS.DELIVERY_DATE             AS planDepartTime,
  RBP.REBINFROMCONTAINER_NAME  AS stockPosition1,
  ''                           AS stockPosition2,
  'Rebin Buffer'               AS workFlowStatus,
  PP.NAME                      AS ppName,
  PO.PICKINGORDER_NO           AS batchNo
FROM OB_REBINREQUESTPOSITION RBP
  LEFT JOIN OB_REBINREQUEST RQ ON RBP.REBINREQUEST_ID = RQ.ID
  LEFT JOIN OB_PICKINGORDER PO ON RQ.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON RBP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
WHERE RBP.AMOUNT_REBINED = 0
      AND RBP.CUSTOMERSHIPMENTPOSITION_ID
          IN (SELECT CSP.ID
              FROM OB_CUSTOMERSHIPMENTPOSITION CSP
                LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
              WHERE CSP.STATE = 620
                    AND CS.DELIVERY_DATE = '2017-09-02 00:00:00')
GROUP BY CS.SHIPMENT_NO, CS.CUSTOMER_NAME, BT.NAME, ITD.SKU_NO, ITD.ITEM_NO, CS.DELIVERY_DATE,
  RBP.REBINFROMCONTAINER_NAME, '', 'Rebin Buffer', PP.NAME, PO.PICKINGORDER_NO;

# Rebined new
SELECT coalesce(SUM(RBP.AMOUNT_REBINED), 0) AS Rebined
FROM OB_PICKINGORDERPOSITION P
  LEFT JOIN OB_REBINREQUESTPOSITION RBP ON P.CUSTOMERSHIPMENTPOSITION_ID = RBP.CUSTOMERSHIPMENTPOSITION_ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION POP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = POP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON POP.SHIPMENT_ID = CS.ID
WHERE
  #   CS.STATE >= '610' AND
  CS.STATE = '630' AND
  RBP.STATE = 'FINISHED'
  AND CS.DELIVERY_DATE = '2017-08-16 03:00:00';

SELECT *
FROM OB_CUSTOMERSHIPMENT CS
WHERE CS.STATE = '630';


SELECT SUM(RBP.AMOUNT_REBINED)
FROM OB_REBINREQUESTPOSITION RBP
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION POP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = POP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON POP.SHIPMENT_ID = CS.ID
WHERE CS.DELIVERY_DATE = '2017-08-16 03:00:00'
      AND POP.SHIPMENT_ID NOT IN (SELECT OBP.SHIPMENT_ID
                                  FROM OBP_OBPROBLEM OBP);



/*9. Rebined 明细*/
SELECT
  C.shipmentID     AS shipmentID,
  C.orderID        AS orderID,
  C.boxType        AS boxType,
  C.SKUNO          AS SKUNO,
  C.SKUID          AS SKUID,
  C.quality        AS quality,
  C.planDepartTime AS planDepartTime,
  C.stockPosition1 AS stockPosition1,
  ''               AS stockPosition2,
  C.workFlowStatus AS workFlowStatus,
  C.ppName         AS ppName,
  C.batchNo        AS batchNo
FROM (
       SELECT
         A.shipmentID,
         A.orderID,
         A.boxType,
         A.SKUNO,
         A.SKUID,
         coalesce((CASE WHEN (A.quality1 - B.AMOUNT) IS NULL
           THEN A.quality1
                   ELSE (A.quality1 - B.AMOUNT) END), 0) AS quality,
         A.planDepartTime,
         A.stockPosition1,
         A.workFlowStatus,
         A.ppName,
         A.batchNo
       FROM
         (SELECT
            CS.SHIPMENT_NO                        AS shipmentID,
            CS.CUSTOMER_NAME                      AS orderID,
            BT.NAME                               AS boxType,
            ITD.SKU_NO                            AS SKUNO,
            ITD.ITEM_NO                           AS SKUID,
            coalesce((SUM(RBP.AMOUNT)), 0)        AS quality1,
            CS.DELIVERY_DATE                      AS planDepartTime,
            concat(RW.NAME, RBP.REBINTOCELL_NAME) AS stockPosition1,
            'Rebined'                             AS workFlowStatus,
            PP.NAME                               AS ppName,
            PO.PICKINGORDER_NO                    AS batchNo
          FROM OB_REBINREQUESTPOSITION RBP
            LEFT JOIN OB_REBINREQUEST RQ ON RBP.REBINREQUEST_ID = RQ.ID
            LEFT JOIN OB_PICKINGORDER PO ON RQ.PICKINGORDER_ID = PO.ID
            LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
            LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
            LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
            LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
            LEFT JOIN MD_ITEMDATA ITD ON RBP.ITEMDATA_ID = ITD.ID
            LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
          WHERE RBP.AMOUNT > 0
                AND RBP.CUSTOMERSHIPMENTPOSITION_ID
                    IN (SELECT CSP.ID
                        FROM OB_CUSTOMERSHIPMENTPOSITION CSP
                          LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
                        WHERE CS.DELIVERY_DATE = '')
          GROUP BY shipmentID, orderID, boxType, SKUNO, SKUID, planDepartTime, stockPosition1,
            workFlowStatus, PP.NAME, PO.PICKINGORDER_NO) A
         LEFT JOIN
         (SELECT
            CS.SHIPMENT_NO,
            ITD.SKU_NO,
            coalesce((SUM(PRP.AMOUNT)), 0) AS AMOUNT
          FROM OB_PACKINGREQUESTPOSITION PRP
            LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON PRP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
            LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
            LEFT JOIN MD_ITEMDATA ITD ON PRP.ITEMDATA_ID = ITD.ID
          WHERE PRP.CUSTOMERSHIPMENTPOSITION_ID
                IN (SELECT CSP.ID
                    FROM OB_CUSTOMERSHIPMENTPOSITION CSP
                      LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
                    WHERE CS.DELIVERY_DATE = '')
          GROUP BY SHIPMENT_NO, SKU_NO) B
           ON A.shipmentID = B.SHIPMENT_NO
              AND A.SKUNO = B.SKU_NO) C
WHERE C.quality != 0;

#  ScanVerify 明细*/  new new
SELECT DISTINCT
  CS.SHIPMENT_NO     AS shipmentID,
  CS.CUSTOMER_NAME   AS orderID,
  BT.NAME            AS boxType,
  ITD.SKU_NO         AS SKUNO,
  ITD.ITEM_NO        AS SKUID,
  CSP.AMOUNT         AS quality,
  CS.DELIVERY_DATE   AS planDepartTime,
  S.NAME             AS stockPosition1,
  PA.NAME            AS stockPosition2,
  'Scan Verify'      AS workFlowStatus,
  PP.NAME            AS ppName,
  PO.PICKINGORDER_NO AS batchNo
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_PACKINGREQUEST PR ON CS.ID = PR.CUSTOMERSHIPMENT_ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_PACKINGSTATION PA ON PR.PACKINGSTATION_ID = PA.ID

  LEFT JOIN OB_PICKINGORDERPOSITION POP ON CSP.ID = POP.CUSTOMERSHIPMENTPOSITION_ID
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID

  LEFT JOIN INV_UNITLOAD_SHIPMENT INV ON CS.ID = INV.SHIPMENT_ID
  LEFT JOIN INV_UNITLOAD UN ON INV.UNITLOAD_ID = UN.ID
  LEFT JOIN MD_STORAGELOCATION S ON UN.STORAGELOCATION_ID = S.ID



  #   LEFT JOIN OB_PICKINGORDER PO ON CS.SHIPMENT_NO = PO.CUSTOMERSHIPMENT_NO
  #   LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID

  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
#   LEFT JOIN INV_UNITLOAD UL ON PR.FROMUNITLOAD_ID = UL.ID
#   LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
#    LEFT JOIN OB_REBINCUSTOMERSHIPMENT RCS ON CS.ID = RCS.CUSTOMERSHIPMENT_ID
#   LEFT JOIN OB_REBINREQUEST RQ ON RCS.REBINREQUEST_ID = RQ.ID
#   LEFT JOIN OB_REBINWALL RW1 ON RQ.REBINWALL1_ID = RW1.ID
#   LEFT JOIN OB_REBINWALL RW2 ON RQ.REBINWALL2_ID = RW2.ID
WHERE
  CS.DELIVERY_DATE = '2017-08-25 02:00:00'
  #   AND CS.STATE >= 600
  AND CS.STATE = 640;

/*10.更新 ScanVerify 明细*/
SELECT
  CS.SHIPMENT_NO     AS shipmentID,
  CS.CUSTOMER_NAME   AS orderID,
  BT.NAME            AS boxType,
  ITD.SKU_NO         AS SKUNO,
  ITD.ITEM_NO        AS SKUID,
  CSP.AMOUNT         AS quality,
  CS.DELIVERY_DATE   AS planDepartTime,
  SL.NAME            AS stockPosition1,
  PA.NAME            AS stockPosition2,
  'Scan Verify'      AS workFlowStatus,
  PP.NAME            AS ppName,
  PO.PICKINGORDER_NO AS batchNo
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_PACKINGREQUEST PR ON CS.ID = PR.CUSTOMERSHIPMENT_ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_PACKINGSTATION PA ON PR.PACKINGSTATION_ID = PA.ID

  LEFT JOIN OB_PICKINGORDER PO ON CS.SHIPMENT_NO = PO.CUSTOMERSHIPMENT_NO
  LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN INV_UNITLOAD UL ON PR.FROMUNITLOAD_ID = UL.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
#    LEFT JOIN OB_REBINCUSTOMERSHIPMENT RCS ON CS.ID = RCS.CUSTOMERSHIPMENT_ID
#   LEFT JOIN OB_REBINREQUEST RQ ON RCS.REBINREQUEST_ID = RQ.ID
#   LEFT JOIN OB_REBINWALL RW1 ON RQ.REBINWALL1_ID = RW1.ID
#   LEFT JOIN OB_REBINWALL RW2 ON RQ.REBINWALL2_ID = RW2.ID
WHERE
  CS.DELIVERY_DATE = '2017-08-16 03:00:00'
  AND CS.STATE >= 600
  AND CS.STATE <= 640;


/*10. ScanVerify 明细*/
SELECT
  CS.SHIPMENT_NO     AS shipmentID,
  CS.CUSTOMER_NAME   AS orderID,
  BT.NAME            AS boxType,
  ITD.SKU_NO         AS SKUNO,
  ITD.ITEM_NO        AS SKUID,
  PRP.AMOUNT         AS quality,
  CS.DELIVERY_DATE   AS planDepartTime,
  (CASE WHEN RCS.REBINWALL_INDEX = 1
    THEN concat(RW1.NAME, RCS.REBINCELL_NAME)
   WHEN RCS.REBINWALL_INDEX = 2
     THEN concat(RW2.NAME, RCS.REBINCELL_NAME)
   ELSE '' END)      AS stockPosition1,
  ''                 AS stockPosition2,
  'Scan Verify'      AS workFlowStatus,
  PP.NAME            AS ppName,
  PO.PICKINGORDER_NO AS batchNo
FROM OB_PACKINGREQUEST PR
  LEFT JOIN OB_PACKINGREQUESTPOSITION PRP ON PR.ID = PRP.PACKINGREQUEST_ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON PRP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON PRP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_REBINCUSTOMERSHIPMENT RCS ON CS.ID = RCS.CUSTOMERSHIPMENT_ID
  LEFT JOIN OB_REBINREQUEST RQ ON RCS.REBINREQUEST_ID = RQ.ID
  LEFT JOIN OB_PICKINGORDER PO ON RQ.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_REBINWALL RW1 ON RQ.REBINWALL1_ID = RW1.ID
  LEFT JOIN OB_REBINWALL RW2 ON RQ.REBINWALL2_ID = RW2.ID
WHERE PRP.CUSTOMERSHIPMENTPOSITION_ID
      IN (SELECT CSP.ID
          FROM OB_CUSTOMERSHIPMENT CS
            LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
          WHERE CS.STATE = '640'
                AND CS.DELIVERY_DATE = '2017-08-16 03:00:00');

/*11. Packed 明细*/
SELECT
  A.SHIPMENT_NO   AS shipmentID,
  #   A.ORDER_NO      AS orderID,
  A.NAME          AS boxType,
  A.SKU_NO        AS SKUNO,
  A.ITEM_NO       AS SKUID,
  A.AMOUNT        AS quality,
  A.DELIVERY_DATE AS planDepartTime,
  A.cell          AS stockPosition1,
  ''              AS stockPosition2,
  'Packed'        AS workFlowStatus,
  A.ppName        AS ppName,
  A.batchNo       AS batchNo

FROM (SELECT
        CSP.ID,
        CS.SHIPMENT_NO,
        #         CO.ORDER_NO,
        BT.NAME,
        ITD.SKU_NO,
        ITD.ITEM_NO,
        CSP.AMOUNT,
        CS.DELIVERY_DATE,
        B.NAME            AS ppName,
        B.PICKINGORDER_NO AS batchNo,
        S.NAME            AS cell
      FROM OB_CUSTOMERSHIPMENT CS
        LEFT JOIN OB_PICKINGCATEGORY PC ON CS.PICKINGCATEGORY_ID = PC.ID
        LEFT JOIN OB_PROCESSPATH PP ON PC.PROCESSPATH_ID = PP.ID
        LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
        LEFT JOIN INV_UNITLOAD_SHIPMENT INV ON CS.ID = INV.SHIPMENT_ID
        LEFT JOIN INV_UNITLOAD UN ON INV.UNITLOAD_ID = UN.ID
        LEFT JOIN MD_STORAGELOCATION S ON UN.STORAGELOCATION_ID = S.ID
        LEFT JOIN (SELECT DISTINCT
                     POP.CUSTOMERSHIPMENTPOSITION_ID,
                     PO.PICKINGORDER_NO,
                     PP.NAME
                   FROM OB_PICKINGORDER PO
                     LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
                     LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID) B
          ON CSP.ID = B.CUSTOMERSHIPMENTPOSITION_ID
        LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
        LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
        LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
      WHERE CS.DELIVERY_DATE = '2017-09-05 00:00:00'
            AND CS.STATE = '650') A;


/*12. Problem 明细*/
SELECT
  A.SHIPMENT_NO           AS shipmentID,
  A.ORDER_NO              AS orderID,
  A.NAME                  AS boxType,
  A.SKU_NO                AS SKUNO,
  A.ITEM_NO               AS SKUID,
  coalesce((A.AMOUNT), 0) AS quality,
  A.DELIVERY_DATE         AS planDepartTime,
  A.SHIPMENT_NO           AS stockPosition1,
  A.SORT_CODE             AS stockPosition2,
  'Problem'               AS workFlowStatus,
  A.PPNAME                AS ppName,
  A.PICKINGORDER_NO       AS batchNo
# FROM ANDONOUTBOUND AO LEFT JOIN
FROM OBP_OBPROBLEM AO
  LEFT JOIN OB_CUSTOMERSHIPMENT CSM ON AO.SHIPMENT_ID = CSM.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSMP ON CSM.ID = CSMP.SHIPMENT_ID
  LEFT JOIN
  (SELECT
     CSP.ID,
     CS.SHIPMENT_NO,
     CO.ORDER_NO,
     BT.NAME,
     ITD.SKU_NO,
     ITD.ITEM_NO,
     CSP.AMOUNT,
     CS.DELIVERY_DATE,
     CS.SORT_CODE,
     B.NAME AS PPNAME,
     B.PICKINGORDER_NO
   FROM OB_CUSTOMERSHIPMENT CS
     LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
     LEFT JOIN (SELECT DISTINCT
                  POP.CUSTOMERSHIPMENTPOSITION_ID,
                  PO.PICKINGORDER_NO,
                  PP.NAME
                FROM OB_PICKINGORDER PO
                  LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
                  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID) B
       ON CSP.ID = B.CUSTOMERSHIPMENTPOSITION_ID
     LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
     LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
     LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
   WHERE CS.DELIVERY_DATE = '2017-08-16 03:00:00') A
    ON CSMP.ID = A.ID
WHERE AO.STATE = 'unsolved';


/* 更新 Problem*/
SELECT DISTINCT
  CS.SHIPMENT_NO            AS shipmentID,
  CS.CUSTOMER_NAME          AS orderID,
  BT.NAME                   AS boxType,
  ITD.SKU_NO                AS SKUNO,
  ITD.ITEM_NO               AS SKUID,
  coalesce((CSP.AMOUNT), 0) AS quality,
  CS.DELIVERY_DATE          AS planDepartTime,
  OB.CONTAINER              AS stockPosition1,
  CS.SORT_CODE              AS stockPosition2,
  'Problem'                 AS workFlowStatus,
  PP.NAME                   AS ppName,
  PO.PICKINGORDER_NO        AS batchNo
FROM OBP_OBPROBLEM OB
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON OB.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN OB_PICKINGORDERPOSITION POP ON CSP.ID = POP.CUSTOMERSHIPMENTPOSITION_ID
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
WHERE OB.STATE = 'unsolved'
      AND PO.STATE = '700'
      AND CS.DELIVERY_DATE = '2017-09-01 00:00:00';

# new  new 最新版 Problem 明细
SELECT DISTINCT
  A.SHIPMENT_NO     AS shipmentID,
  A.ORDER_NO        AS orderID,
  A.NAME            AS boxType,
  A.SKU_NO          AS SKUNO,
  A.ITEM_NO         AS SKUID,
  A.AMOUNT          AS quality,
  A.DELIVERY_DATE   AS planDepartTime,
  A.stockPosition1  AS stockPosition1,
  A.SORT_CODE       AS stockPosition2,
  'Problem'         AS workFlowStatus,
  A.PPNAME          AS ppName,
  A.PICKINGORDER_NO AS batchNo
FROM
  (SELECT DISTINCT
     CS.ID,
     CS.SHIPMENT_NO,
     CO.ORDER_NO,
     BT.NAME,
     ITD.SKU_NO,
     ITD.ITEM_NO,
     CSP.amount,
     CS.DELIVERY_DATE,
     CS.SORT_CODE,
     B.NAME                                AS PPNAME,
     B.PICKINGORDER_NO,
     concat(RW.NAME, RBP.REBINTOCELL_NAME) AS stockPosition1
   FROM OB_CUSTOMERSHIPMENT CS
     LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
     LEFT JOIN (SELECT DISTINCT
                  POP.CUSTOMERSHIPMENTPOSITION_ID,
                  PO.PICKINGORDER_NO,
                  PP.NAME
                FROM OB_PICKINGORDER PO
                  LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
                  LEFT JOIN OB_PICKINGORDER PR ON POP.PICKINGORDER_ID = PR.ID
                  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
                WHERE PR.STATE = '700') B
       ON CSP.ID = B.CUSTOMERSHIPMENTPOSITION_ID
     LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
     LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
     LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
     LEFT JOIN OB_REBINREQUESTPOSITION RBP ON CSP.ID = RBP.CUSTOMERSHIPMENTPOSITION_ID
     LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
   WHERE CS.DELIVERY_DATE = '2017-08-23 02:00:00' AND CS.state = '1100') A;
=





/*12. 更新 Problem 明细*/
SELECT DISTINCT
  A.SHIPMENT_NO     AS shipmentID,
  A.ORDER_NO        AS orderID,
  A.NAME            AS boxType,
  A.SKU_NO          AS SKUNO,
  A.ITEM_NO         AS SKUID,
  A.AMOUNT          AS quality,
  A.DELIVERY_DATE   AS planDepartTime,
  A.SHIPMENT_NO     AS stockPosition1,
  A.SORT_CODE       AS stockPosition2,
  'Problem'         AS workFlowStatus,
  A.PPNAME          AS ppName,
  A.PICKINGORDER_NO AS batchNo
FROM
  (SELECT DISTINCT
     CS.ID,
     CS.SHIPMENT_NO,
     CO.ORDER_NO,
     BT.NAME,
     ITD.SKU_NO,
     ITD.ITEM_NO,
     CSP.AMOUNT,
     CS.DELIVERY_DATE,
     CS.SORT_CODE,
     B.NAME AS PPNAME,
     B.PICKINGORDER_NO
   FROM OB_CUSTOMERSHIPMENT CS
     LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
     LEFT JOIN (SELECT DISTINCT
                  POP.CUSTOMERSHIPMENTPOSITION_ID,
                  PO.PICKINGORDER_NO,
                  PP.NAME
                FROM OB_PICKINGORDER PO
                  LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
                  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID) B
       ON CSP.ID = B.CUSTOMERSHIPMENTPOSITION_ID
     LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
     LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
     LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
   WHERE CS.DELIVERY_DATE = '2017-08-16 00:00:00') A
  LEFT JOIN OBP_OBPROBLEM AO
    ON A.ID = AO.SHIPMENT_ID
WHERE AO.STATE = 'unsolved';
      AND A.PPNAME = '';

/* 更新 Problem  new 明细*/
SELECT DISTINCT
  CS.SHIPMENT_NO            AS shipmentID,
  CS.CUSTOMER_NAME          AS orderID,
  BT.NAME                   AS boxType,
  ITD.SKU_NO                AS SKUNO,
  ITD.ITEM_NO               AS SKUID,
  coalesce((CSP.AMOUNT), 0) AS quality,
  CS.DELIVERY_DATE          AS planDepartTime,
  OB.CONTAINER              AS stockPosition1,
  CS.SORT_CODE              AS stockPosition2,
  'Problem'                 AS workFlowStatus,
  PP.NAME                   AS ppName,
  PO.PICKINGORDER_NO        AS batchNo
FROM OBP_OBPROBLEM OB
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON OB.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN OB_PICKINGORDERPOSITION POP ON CSP.ID = POP.CUSTOMERSHIPMENTPOSITION_ID
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_PICKINGUNITLOAD PUL ON POP.PICKTOUNITLOAD_ID = PUL.ID
WHERE OB.STATE = 'unsolved'
      AND PO.STATE = '700'
      AND CS.DELIVERY_DATE = '2017-09-01 00:00:00';

/*13. Sorted 明细*/
SELECT
  A.SHIPMENT_NO     AS shipmentID,
  A.ORDER_NO        AS orderID,
  A.NAME            AS boxType,
  A.SKU_NO          AS SKUNO,
  A.ITEM_NO         AS SKUID,
  A.AMOUNT          AS quality,
  A.DELIVERY_DATE   AS planDepartTime,
  A.SHIPMENT_NO     AS stockPosition1,
  A.SORT_CODE       AS stockPosition2,
  'Loaded'          AS workFlowStatus,
  A.PPNAME          AS ppName,
  A.PICKINGORDER_NO AS batchNo
FROM (SELECT
        CSP.ID,
        CS.SHIPMENT_NO,
        CO.ORDER_NO,
        BT.`NAME`,
        ITD.SKU_NO,
        ITD.ITEM_NO,
        CSP.AMOUNT,
        CS.DELIVERY_DATE,
        CS.SORT_CODE,
        B.NAME AS PPNAME,
        B.PICKINGORDER_NO
      FROM OB_CUSTOMERSHIPMENT CS
        LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID

        LEFT JOIN (SELECT DISTINCT
                     POP.CUSTOMERSHIPMENTPOSITION_ID,
                     PO.PICKINGORDER_NO,
                     PP.NAME
                   FROM OB_PICKINGORDER PO
                     LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
                     LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID) B
          ON CSP.ID = B.CUSTOMERSHIPMENTPOSITION_ID
        LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
        LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
        LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
      WHERE
        CS.DELIVERY_DATE = '2017-08-23 02:00:00'
        AND CS.STATE = '660') A;


SELECT
  CS.SHIPMENT_NO     AS shipmentID,
  CS.CUSTOMER_NAME   AS orderID,
  BT.NAME            AS boxType,
  ITD.SKU_NO         AS SKUNO,
  ITD.ITEM_NO        AS SKUID,
  POP.AMOUNT         AS quality,
  CS.DELIVERY_DATE   AS planDepartTime,
  SL.NAME            AS stockPosition1,
  ''                 AS stockPosition2,
  'Ready to Pick'    AS workFlowStatus,
  PP.NAME            AS ppName,
  PO.PICKINGORDER_NO AS batchNo
FROM OB_PICKINGORDERPOSITION POP
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON POP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_PICKINGCATEGORY PC ON CS.PICKINGCATEGORY_ID = PC.ID
  LEFT JOIN OB_PROCESSPATH PP ON PC.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON POP.ITEMDATA_ID = ITD.ID
  LEFT JOIN INV_STOCKUNIT ST ON POP.PICKFROMSTOCKUNIT_ID = ST.ID
  LEFT JOIN INV_UNITLOAD UL ON ST.UNITLOAD_ID = UL.ID
  LEFT JOIN MD_STORAGELOCATION SL ON UL.STORAGELOCATION_ID = SL.ID
WHERE
  #                    POP.STATE = '200'
  #                        AND
  POP.CUSTOMERSHIPMENTPOSITION_ID
  IN (SELECT CSP.ID
      FROM OB_CUSTOMERSHIPMENTPOSITION CSP
        LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
      WHERE CS.DELIVERY_DATE LIKE '%');


SELECT coalesce(SUM(POP.AMOUNT - coalesce(POP.AMOUNT_PICKED, 0)), 0) AS PickingNotYetPicked
FROM OB_PICKINGORDERPOSITION POP
  LEFT JOIN OB_PICKINGORDER PO ON POP.PICKINGORDER_ID = PO.ID
WHERE
  PO.STATE < 600 AND
  POP.CUSTOMERSHIPMENTPOSITION_ID
  IN (SELECT CSP.ID
      FROM OB_CUSTOMERSHIPMENTPOSITION CSP
        LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
      WHERE CS.DELIVERY_DATE = '2017-08-16 03:00:00')
  AND POP.PICKINGORDER_ID IS NOT NULL;

#  rebined new new 2017.8.7
SELECT DISTINCT
  CS.SHIPMENT_NO                        AS shipmentID,
  CS.CUSTOMER_NAME                      AS orderID,
  BT.NAME                               AS boxType,
  ITD.SKU_NO                            AS SKUNO,
  ITD.ITEM_NO                           AS SKUID,
  coalesce((SUM(RBP.AMOUNT)), 0)        AS quality,
  CS.DELIVERY_DATE                      AS planDepartTime,
  concat(RW.NAME, RBP.REBINTOCELL_NAME) AS stockPosition1,
  ''                                    AS stockPosition2,
  'Rebined'                             AS workFlowStatus,
  PP.NAME                               AS ppName,
  PO.PICKINGORDER_NO                    AS batchNo
FROM OB_REBINREQUESTPOSITION RBP
  LEFT JOIN OB_REBINREQUEST RQ ON RBP.REBINREQUEST_ID = RQ.ID
  LEFT JOIN OB_PICKINGORDER PO ON RQ.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON RBP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
WHERE (CSP.STATE = '620' OR CS.STATE = '630')
      AND CS.DELIVERY_DATE = '2017-08-16 03:00:00'
      AND RBP.STATE = 'FINISHED'
GROUP BY shipmentID, orderID, boxType, SKUNO, SKUID, planDepartTime, stockPosition1,
  workFlowStatus, PP.NAME, PO.PICKINGORDER_NO;

#  rebined明细 new new 2017.8.11
SELECT DISTINCT
  CS.SHIPMENT_NO                        AS shipmentID,
  CS.CUSTOMER_NAME                      AS orderID,
  BT.NAME                               AS boxType,
  ITD.SKU_NO                            AS SKUNO,
  ITD.ITEM_NO                           AS SKUID,
  coalesce(sum(RBP.AMOUNT), 0)          AS quality,
  CS.DELIVERY_DATE                      AS planDepartTime,
  concat(RW.NAME, RBP.REBINTOCELL_NAME) AS stockPosition1,
  ''                                    AS stockPosition2,
  'Rebined'                             AS workFlowStatus,
  PP.NAME                               AS ppName,
  PO.PICKINGORDER_NO                    AS batchNo
FROM OB_REBINREQUESTPOSITION RBP
  LEFT JOIN OB_REBINREQUEST RQ ON RBP.REBINREQUEST_ID = RQ.ID
  LEFT JOIN OB_PICKINGORDER PO ON RQ.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON RBP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
WHERE 1 = 1
      #  and CS.ID NOT IN (SELECT CS.ID FROM OB_CUSTOMERSHIPMENT CS WHERE CS.STATE = '1100')
      AND CS.DELIVERY_DATE = '2017-08-16 03:00:00'
      AND RBP.STATE <> 'RAW'
      AND RBP.STATE <> 'LOSE'
#   AND PO.STATE = '700'
GROUP BY shipmentID, orderID, boxType, SKUNO, SKUID, planDepartTime, stockPosition1,
  workFlowStatus, ppName, batchNo;

#  2017.08.13 rebined 明细 test test test  最新版
SELECT DISTINCT
  CS.SHIPMENT_NO                        AS shipmentID,
  CS.CUSTOMER_NAME                      AS orderID,
  BT.NAME                               AS boxType,
  ITD.SKU_NO                            AS SKUNO,
  ITD.ITEM_NO                           AS SKUID,
  coalesce(sum(RBP.AMOUNT), 0)          AS quality,
  CS.DELIVERY_DATE                      AS planDepartTime,
  concat(RW.NAME, RBP.REBINTOCELL_NAME) AS stockPosition1,
  ''                                    AS stockPosition2,
  'Rebined'                             AS workFlowStatus,
  PP.NAME                               AS ppName,
  PO.PICKINGORDER_NO                    AS batchNo
FROM OB_REBINREQUESTPOSITION RBP
  LEFT JOIN OB_REBINREQUEST RQ ON RBP.REBINREQUEST_ID = RQ.ID
  LEFT JOIN OB_PICKINGORDER PO ON RQ.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON RBP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
WHERE 1 = 1
      AND ((PO.STATE <> '700') OR (PO.STATE = '700' AND CS.STATE = '630' AND CS.ID NOT IN (SELECT CS.ID
                                                                                           FROM OB_CUSTOMERSHIPMENT CS
                                                                                           WHERE CS.STATE = '1100')))
      AND CS.DELIVERY_DATE = '2017-08-23 02:00:00'
      AND RBP.STATE <> 'RAW'
      AND RBP.STATE <> 'LOSE'
GROUP BY shipmentID, orderID, boxType, SKUNO, SKUID, planDepartTime, stockPosition1,
  workFlowStatus, ppName, batchNo;

#  rebined new new 2017.8.11

SELECT DISTINCT
  CS.SHIPMENT_NO                        AS shipmentID,
  CS.CUSTOMER_NAME                      AS orderID,
  BT.NAME                               AS boxType,
  ITD.SKU_NO                            AS SKUNO,
  ITD.ITEM_NO                           AS SKUID,
  coalesce(sum(RBP.AMOUNT), 0)          AS quality,
  CS.DELIVERY_DATE                      AS planDepartTime,
  concat(RW.NAME, RBP.REBINTOCELL_NAME) AS stockPosition1,
  ''                                    AS stockPosition2,
  'Rebined'                             AS workFlowStatus,
  PP.NAME                               AS ppName,
  PO.PICKINGORDER_NO                    AS batchNo
FROM OB_REBINREQUESTPOSITION RBP
  LEFT JOIN OB_REBINREQUEST RQ ON RBP.REBINREQUEST_ID = RQ.ID
  LEFT JOIN OB_PICKINGORDER PO ON RQ.PICKINGORDER_ID = PO.ID
  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON RBP.CUSTOMERSHIPMENTPOSITION_ID = CSP.ID
  LEFT JOIN OB_CUSTOMERSHIPMENT CS ON CSP.SHIPMENT_ID = CS.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON RBP.ITEMDATA_ID = ITD.ID
  LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
WHERE 1 = 1
      AND CS.ID NOT IN (SELECT CS.ID
                        FROM OB_CUSTOMERSHIPMENT CS
                        WHERE CS.STATE = '1100')
      AND CS.DELIVERY_DATE = '2017-08-16 03:00:00'
      AND RBP.STATE <> 'RAW'
      AND RBP.STATE <> 'LOSE'
      AND PO.STATE = '700'
GROUP BY shipmentID, orderID, boxType, SKUNO, SKUID, planDepartTime, stockPosition1,
  workFlowStatus, ppName, batchNo;

# problem 最最最新版  2017.8.16
SELECT DISTINCT
  A.SHIPMENT_NO     AS shipmentID,
  A.ORDER_NO        AS orderID,
  A.NAME            AS boxType,
  A.SKU_NO          AS SKUNO,
  A.ITEM_NO         AS SKUID,
  A.AMOUNT          AS quality,
  A.DELIVERY_DATE   AS planDepartTime,
  A.cellName        AS stockPosition1,
  A.SORT_CODE       AS stockPosition2,
  'Problem'         AS workFlowStatus,
  A.PPNAME          AS ppName,
  A.PICKINGORDER_NO AS batchNo
FROM
  (SELECT DISTINCT
     CS.ID,
     CS.SHIPMENT_NO,
     CO.ORDER_NO,
     BT.NAME,
     ITD.SKU_NO,
     ITD.ITEM_NO,
     CSP.AMOUNT,
     CS.DELIVERY_DATE,
     CS.SORT_CODE,
     B.NAME AS PPNAME,
     B.PICKINGORDER_NO,
     S.NAME AS cellName
   FROM OB_CUSTOMERSHIPMENT CS
     LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
     LEFT JOIN INV_UNITLOAD_SHIPMENT INV ON CS.ID = INV.SHIPMENT_ID
     LEFT JOIN INV_UNITLOAD UN ON INV.UNITLOAD_ID = UN.ID
     LEFT JOIN MD_STORAGELOCATION S ON UN.STORAGELOCATION_ID = S.ID
     LEFT JOIN (SELECT DISTINCT
                  POP.CUSTOMERSHIPMENTPOSITION_ID,
                  PO.PICKINGORDER_NO,
                  PP.NAME
                FROM OB_PICKINGORDER PO
                  LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
                  LEFT JOIN OB_PICKINGORDER PR ON POP.PICKINGORDER_ID = PR.ID
                  LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID
                WHERE PR.STATE = '700') B
       ON CSP.ID = B.CUSTOMERSHIPMENTPOSITION_ID
     LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
     LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
     LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
   #      LEFT JOIN OB_REBINREQUESTPOSITION RBP ON CSP.ID = RBP.CUSTOMERSHIPMENTPOSITION_ID
   #      LEFT JOIN OB_REBINWALL RW ON RBP.REBINWALL_ID = RW.ID
   #      LEFT JOIN OBP_OBPCELL ce ON RW.ID = ce.WALL_ID
   WHERE CS.DELIVERY_DATE = '2017-08-25 02:00:00'
         AND CS.STATE = '1100') A;

# sorted 2017.8.16
SELECT
  A.SHIPMENT_NO     AS shipmentID,
  A.ORDER_NO        AS orderID,
  A.NAME            AS boxType,
  A.SKU_NO          AS SKUNO,
  A.ITEM_NO         AS SKUID,
  A.AMOUNT          AS quality,
  A.DELIVERY_DATE   AS planDepartTime,
  A.cell            AS stockPosition1,
  A.SORT_CODE       AS stockPosition2,
  'Sorted'          AS workFlowStatus,
  A.PPNAME          AS ppName,
  A.PICKINGORDER_NO AS batchNo
FROM (SELECT
        CSP.ID,
        CS.SHIPMENT_NO,
        CO.ORDER_NO,
        BT.`NAME`,
        ITD.SKU_NO,
        ITD.ITEM_NO,
        CSP.AMOUNT,
        CS.DELIVERY_DATE,
        CS.SORT_CODE,
        B.NAME AS PPNAME,
        B.PICKINGORDER_NO,
        S.NAME AS cell
      FROM OB_CUSTOMERSHIPMENT CS
        LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
        LEFT JOIN INV_UNITLOAD_SHIPMENT INV ON CS.ID = INV.SHIPMENT_ID
        LEFT JOIN INV_UNITLOAD UN ON INV.UNITLOAD_ID = UN.ID
        LEFT JOIN MD_STORAGELOCATION S ON UN.STORAGELOCATION_ID = S.ID
        LEFT JOIN (SELECT DISTINCT
                     POP.CUSTOMERSHIPMENTPOSITION_ID,
                     PO.PICKINGORDER_NO,
                     PP.NAME
                   FROM OB_PICKINGORDER PO
                     LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
                     LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID) B
          ON CSP.ID = B.CUSTOMERSHIPMENTPOSITION_ID
        LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
        LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
        LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
      WHERE
        CS.DELIVERY_DATE = '2017-08-23 02:00:00'
        AND CS.STATE = '660') A;

# loaded
SELECT
  CS.SHIPMENT_NO    AS shipmentID,
  CO.ORDER_NO       AS orderID,
  BT.`NAME`         AS boxType,
  ITD.SKU_NO        AS SKUNO,
  ITD.ITEM_NO       AS SKUID,
  CSP.AMOUNT        AS quality,
  CS.DELIVERY_DATE  AS planDepartTime,
  S.NAME            AS stockPosition1,
  CS.SORT_CODE      AS stockPosition2,
  'Loaded'          AS workFlowStatus,
  B.NAME            AS ppName,
  B.PICKINGORDER_NO AS batchNo
FROM OB_CUSTOMERSHIPMENT CS
  LEFT JOIN OB_CUSTOMERSHIPMENTPOSITION CSP ON CS.ID = CSP.SHIPMENT_ID
  LEFT JOIN INV_UNITLOAD_SHIPMENT INV ON CS.ID = INV.SHIPMENT_ID
  LEFT JOIN INV_UNITLOAD UN ON INV.UNITLOAD_ID = UN.ID
  LEFT JOIN MD_STORAGELOCATION S ON UN.STORAGELOCATION_ID = S.ID
  LEFT JOIN (SELECT DISTINCT
               POP.CUSTOMERSHIPMENTPOSITION_ID,
               PO.PICKINGORDER_NO,
               PP.NAME
             FROM OB_PICKINGORDER PO
               LEFT JOIN OB_PICKINGORDERPOSITION POP ON PO.ID = POP.PICKINGORDER_ID
               LEFT JOIN OB_PROCESSPATH PP ON PO.PROCESSPATH_ID = PP.ID) B
    ON CSP.ID = B.CUSTOMERSHIPMENTPOSITION_ID
  LEFT JOIN OB_CUSTOMERORDER CO ON CS.ORDER_ID = CO.ID
  LEFT JOIN OB_BOXTYPE BT ON CS.BOXTYPE_ID = BT.ID
  LEFT JOIN MD_ITEMDATA ITD ON CSP.ITEMDATA_ID = ITD.ID
WHERE
  CS.DELIVERY_DATE = '2017-08-23 02:00:00'
  AND CS.STATE = '670';

















