/*
 * 本包实现了一个log4j信息到UI的功能，其中包含了一个输出到
 * JTextPane的演示程序
 * 陈庆余 2014-02-18
 */
package com.aricojf.platform.util.aricojflog4j;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.xml.stream.events.StartDocument;
import org.apache.log4j.Logger;

/**
 * 此程序演示了log4j输出信息到一个jTextPane组件。
 * 注意：必须实现AricoJFLog2UIInterface接口,必须与log4j.xml配置文件结合应用 
 * 重要提示： 
 * 1.可以用log4j本身的4种级别
 * 2.也可以自己定义的级别，
 * 为了用在UI中，规定AricoJFLevel为21000，高于log4j本身的 INFO级别。
 *
 * @author AricoChen <陈庆余 AricoChen@tom.com>
 */
public class AricoJFLog2UITestApp extends javax.swing.JFrame implements AricoJFLog2UIInterface {
      //下面是log4j本身级别
    // Logger loger = Logger.getLogger(this.getClass().getName());
    //下面这行是自定义日志级别(21000:AricoJFLevel)
    AricoJFLog loger = AricoJFLog.getLogger(AricoJFLog2UITestApp.class.getName());

    /**
     * Creates new form AricoJFTextAppenderTest
     */
    public AricoJFLog2UITestApp() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setTitle("Log4j日志（包括自定义级别到JTextPane例子)");
        //准备调用log4j到UI
        AricoJFLog2UIAppderUtil.setAricoJFTextI(this);
    }

    //此方法是实现了接口AricoJFLogTextI中的唯一方法，在此进行处理要显示log4j日志的UI
    public void setLoggerMsg(final String msg, final String logType) {
        final int cacheRows = 50;//缓冲行数
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                StyledDocument doc = jTextPane1.getStyledDocument(); // 获得JTextPane的Document
                int currentLines = jTextPane1.getDocument().getDefaultRootElement().getElementCount();
                if (currentLines >= cacheRows) {//总行数超过缓冲行后，自动清空
                    try {
                        doc.remove(0, doc.getLength());
                    } catch (Exception e) {
                    }
                }
                try {
                    SimpleAttributeSet attrSet = new SimpleAttributeSet();
                    StyleConstants.setFontFamily(attrSet, "宋体");//字体
                    StyleConstants.setFontSize(attrSet, 20);//字体大小
                    if (logType.trim().equals("INFO")) {
                        StyleConstants.setBold(attrSet, true);//黑体
                        StyleConstants.setItalic(attrSet, true);//斜体
                        StyleConstants.setForeground(attrSet, Color.BLUE);//前景颜色
                        StyleConstants.setBackground(attrSet, Color.BLACK);//背景颜色
                    } else {
                        StyleConstants.setBold(attrSet, false);//黑体
                        StyleConstants.setItalic(attrSet, false);//斜体
                        StyleConstants.setForeground(attrSet, Color.RED);//前景颜色
                        StyleConstants.setBackground(attrSet, Color.WHITE);//背景颜色   
                    }
                    doc.insertString(doc.getLength(), msg, attrSet);
                } catch (BadLocationException be) {
                }
            }
        });
    }

    public void test() {
        new Thread() {
            public void run() {
                for (int i = 0; i < 10000; i++) {
                    //下面是log4j本身自带级别使用方法
                    loger.info("INFO:" + i);
                    //下面一行是自定义级别方法
                    loger.aricoJFLog("OK:" + i);
                    try {
                        Thread.sleep(300);
                    } catch (Exception e) {

                    }

                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jButton1.setText("Log4j开始");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        test();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        *//* Set the Nimbus look and feel *//*
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        *//* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AricoJFLog2UITestApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AricoJFLog2UITestApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AricoJFLog2UITestApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AricoJFLog2UITestApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        *//* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AricoJFLog2UITestApp test = new AricoJFLog2UITestApp();
                test.setVisible(true);

            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
