/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mushiny.kivaconfigtool;

import com.mushiny.rcs.global.RCSLogConfig;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aricochen
 */
public class KivaConfigTool extends javax.swing.JFrame {

    String title = "AGV调试工具@1.0  版权所有：苏州牧星智能科技有限公司 Mushiny";

    static {
        String log4jConfig = System.getProperty("log4j");
        String rcsConfig = System.getProperty("rcsconfig");
        if (log4jConfig != null && (new File(log4jConfig)).exists()) {
//            PropertyConfigurator.configureAndWatch(log4jConfig, 60000);
            System.out.println("####====log4j配置：" + log4jConfig);
        } else {
            System.out.println("####====log4j配置：无外部配置文件，采用默认配置信息!");
        }
        if (rcsConfig != null && (new File(rcsConfig)).exists()) {
            RCSLogConfig.getInstance().setRcsConfigFile(rcsConfig);
            System.out.println("####====RCS配置：" + rcsConfig);
        } else {
            System.out.println("####====RCS配置：无外部配置文件，采用默认配置信息!");
        }

    }
    ConfigWindowPanel window;

    public GridBagLayout gbaglayout;
    public GridBagConstraints constraints;

    /**
     * Creates new form KivaConfigTool
     */
    public KivaConfigTool() {
        initComponents();
        setGBL();
        setTitle(title);
        setPreferredSize(new Dimension(1024, 768));
        //关闭按钮退出总线程
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //最大化主界面
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        window = new ConfigWindowPanel();
        getContentPane().add(window, constraints);
        window.initUI();
    }

    public void setGBL() {
        gbaglayout = new GridBagLayout();
        constraints = new GridBagConstraints();
        constraints.gridx = 0;
        constraints.gridy = 0;
        constraints.gridwidth = 1;
        constraints.gridheight = 1;
        constraints.anchor = GridBagConstraints.CENTER;
        constraints.fill = GridBagConstraints.BOTH;
        constraints.weightx = 1;
        constraints.weighty = 1;
        constraints.insets = new Insets(0, 0, 0, 0);
        constraints.ipadx = 0;
        constraints.ipady = 0;
    }
    // 一般性提示信息

    public void ShowCommonInfo(String Info) {
        JOptionPane.showMessageDialog(this, Info, "提示",
                JOptionPane.INFORMATION_MESSAGE, null);
    }

    // 警告提示信息
    public void ShowWarningInfo(String Info) {
        JOptionPane.showMessageDialog(this, Info, "提示",
                JOptionPane.WARNING_MESSAGE, null);
    }

    // 出错提示信息
    public void ShowErrorInfo(String Info) {
        JOptionPane.showMessageDialog(this, Info, "提示",
                JOptionPane.ERROR_MESSAGE, null);
    }

    // 询问提示信息
    public int ShowAskInfo(String Info) {
        return JOptionPane.showOptionDialog(this, Info, "提示",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                null, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         /*Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
         If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KivaConfigTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KivaConfigTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KivaConfigTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KivaConfigTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

//         Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KivaConfigTool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
