package com.mushiny.mq;

/**
 * Created by Tank.li on 2017/7/3.
 */
public interface ISender {
    /* 以下是下发的指令 WCS--->RCS 这些是队列也是路由的名字*/
    String WCS_RCS_MAP_RESPONSE = "WCS_RCS_MAP_RESPONSE";
    String WCS_RCS_ROBOT_LOGIN_RESPONSE = "WCS_RCS_ROBOT_LOGIN_RESPONSE";
    String WCS_RCS_AGV_SERIESPATH = "WCS_RCS_AGV_SERIESPATH";
    String WCS_RCS_AGV_PARKING_NEAREST = "WCS_RCS_AGV_PARKING_NEAREST";
    String WCS_RCS_URGENT_STOP = "WCS_RCS_URGENT_STOP";
    String WCS_RCS_ALL_MOTOR_CUT = "WCS_RCS_ALL_MOTOR_CUT";
    String WCS_RCS_START_SLEEP = "WCS_RCS_START_SLEEP";
    String WCS_RCS_STOP_SLEEP = "WCS_RCS_STOP_SLEEP";
    String WCS_RCS_CLEAR_ALLPATH = "WCS_RCS_CLEAR_ALLPATH";
    String EXCHANGE = "exchange_other";
    String WCS_MAP_CHANGED = "WCS_MAP_CHANGED";//给地图使用的事件
    String WEBSOCKET_RECEIVE_QUEUE= "WEBSOCKET.RCS.RECEIVE.QUEUE";
    String WCS_RCS_AGV_CHARGE= "WCS_RCS_AGV_CHARGE";
    String WCS_RCS_QUERYROBOT_REQUEST = "WCS_RCS_QUERYROBOT_REQUEST";
    String WCS_RCS_UPDATE_CELLS = "WCS_RCS_UPDATE_CELLS";
    String WCS_MAP_SP_UNWALK_CELL = "WCS_MAP_SP_UNWALK_CELL";
    String WCS_RCS_PODSCAN_PATH = "WCS_RCS_PODSCAN_PATH";
    String WCS_RCS_CHANGING_POD_POSITION = "WCS_RCS_CHANGING_POD_POSITION";
    String WCS_RCS_AGV_PATH_RESEND = "WCS_RCS_AGV_PATH_RESEND";
    String WCS_RCS_REQUEST_ITEM_INFO = "WCS_RCS_REQUEST_ITEM_INFO";
    String WCS_RCS_REQUEST_MEDIA_AGV_CONFIG_PARAMETERS = "WCS_RCS_REQUEST_MEDIA_AGV_CONFIG_PARAMETERS";
    String WCS_RCS_UPDATE_MEDIA_AGV_CONFIG_PARAMETERS = "WCS_RCS_UPDATE_MEDIA_AGV_CONFIG_PARAMETERS";
    String WCS_RCS_CLEAR_MEDIA_ERROR = "WCS_RCS_CLEAR_MEDIA_ERROR";
    String WCS_RCS_REQUEST_ACTION_COMMAND = "WCS_RCS_REQUEST_ACTION_COMMAND";
    String WCS_RCS_MIDEA_CHARGE = "WCS_RCS_MIDEA_CHARGE";
    String WCS_RCS_OFFLINE_ROBOT = "WCS_RCS_OFFLINE_ROBOT";
    //移动监控设备需要的消息
    String RCS_WCS_ROBOT_RT_MD = "RCS_WCS_ROBOT_RT_MD";
    String WCS_ANY_WAREHOUSE_INIT_RESPONSE = "WCS_ANY_WAREHOUSE_INIT_RESPONSE";
    String WCS_ANY_CHARGE_ORDER = "WCS_ANY_CHARGE_ORDER";
    String WCS_ANY_ROBOT_STATUS = "WCS_ANY_ROBOT_STATUS";

}
